// <auto-generated />
using Ejercicio_1EntityFramework;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using System;

namespace Ejercicio_1EntityFramework.Migrations
{
    [DbContext(typeof(DBContext))]
    [Migration("20180813174248_eso")]
    partial class eso
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.1-rtm-125")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Ejercicio_1EntityFramework.Mascota", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<bool>("EstadoAdopcion");

                    b.Property<string>("Nombre");

                    b.Property<string>("Raza");

                    b.HasKey("Id");

                    b.ToTable("Mascotas");
                });

            modelBuilder.Entity("Ejercicio_1EntityFramework.Persona", b =>
                {
                    b.Property<int>("Cedula")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("FechaNacimiento");

                    b.Property<string>("Nombre");

                    b.HasKey("Cedula");

                    b.ToTable("Personas");
                });

            modelBuilder.Entity("Ejercicio_1EntityFramework.Persona_Mascota", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int?>("MascotaId");

                    b.Property<int?>("PersonaCedula");

                    b.HasKey("Id");

                    b.HasIndex("MascotaId");

                    b.HasIndex("PersonaCedula");

                    b.ToTable("Persona_Mascotas");
                });

            modelBuilder.Entity("Ejercicio_1EntityFramework.Persona_Mascota", b =>
                {
                    b.HasOne("Ejercicio_1EntityFramework.Mascota", "Mascota")
                        .WithMany("Persona_Mascota")
                        .HasForeignKey("MascotaId");

                    b.HasOne("Ejercicio_1EntityFramework.Persona", "Persona")
                        .WithMany("Persona_Mascota")
                        .HasForeignKey("PersonaCedula");
                });
#pragma warning restore 612, 618
        }
    }
}
